name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: run cov
        run: |
          go test ./... -cover -coverprofile=coverage.out -json > report.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        # with:
        #   projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
